alias cdproject="cd /mnt/Data/Projects/"
alias cdlearning="cd /mnt/Data/Learning/"
alias cdresources="cd /mnt/Data/Tai-lieu/"
alias cddata="cd /mnt/Data/"
alias cdsetup="cd /mnt/Setup/"

#set -x SCALA_HOME '/usr/local/share/scala'
#set -x PATH $SCALA_HOME/bin $PATH
#set -x ACTIVATOR '/home/supercoder/activator/'
#set -x PATH $ACTIVATOR $PATH
#set -x GOPATH '/mnt/Data/Projects/go'
#set -x GOROOT '/usr/lib/go'
